# Project Name
TARGET = ChebyshevTremolo

# Sources
CPP_SOURCES = ChebyshevTremolo.cpp chebytrem.cpp

# Library Locations
LIBDAISY_DIR = ../../libdaisy
DAISYSP_DIR = ../../DaisySP

DEBUG = 1
OPT = -O0

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
